# Generated by Django 4.0.4 on 2022-04-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_user_bio_alter_user_birthday_alter_user_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
